### ISSUE TITLE
Feed? and Queue?

### ISSUE THREAD

**Issue by abitrolly** [amosbastian/utopian.rocks#19]
The difference between `Feed` and `Queue` is not clear from the website. Maybe buttons could carry some explanation marks.

> abitrolly - Last Saturday at 5:52 PM
> Oh, I see. Thanks for the link. I've just discovered https://utopian.rocks/ from #faq. Still it is not clear what is the connection between "Waiting for review: 34" feed and queue .

> crokkon [mod] - Last Saturday at 5:56 PM
> "waiting for review" are contributions that were not yet reviewed by moderators. Those contributions that are already reviewed and qualify for a potential vote are then shown in the queue.

And point calculation time span also not clear. I've been already voted by @utopian-io during current timespan, but I am still not in the list https://utopian.rocks/points/2018-07-19

**Comment by amosbastian** [comment]
Thanks a lot for the issue - I will definitely get to this and try to resolve this once I get back from holiday (about two weeks from now).

**Comment by abitrolly** [comment]
No worries. Have a good time in UK. :)
