### ISSUE TITLE
Bug 

### ISSUE THREAD

**Issue by omideleayo** [amosbastian/utopian.rocks#23]
Issues with the new homepage, via mobile device. 
Expected behavior : once I open the site, it should have a perfect resolution, and when I click on other options like **awaiting upvote **.

Actual Behavior : The page becomes too extended and I can't serially at a glance. 
I have to adjust screen resolution. 

Phone : Infinix X557
Operating System : Android 7.0

**Comment by amosbastian** [comment]
This is a known bug and unfortunately I'm too bad at making things responsive to fix this, so I'll probably create a task request for this in the future. A workaround for this is zooming out, which should make it work fine on a mobile device. Thanks for reporting it, though!

**Comment by omideleayo** [comment]
OK,  glad to know something would be done about it. 
Unfortunately am not a developer, would have helped. 
Cheers
