### ISSUE TITLE
Incorrect redirection of github repo in moderator's page

### ISSUE THREAD

**Issue by espoem** [amosbastian/utopian.rocks#3]
### Expected behaviour

I believe that the link should point to the actual GitHub repository or to the feed with reviewed contributions in Utopian.

### Actual behaviour

Link redirects to an invalid route.

![image](https://user-images.githubusercontent.com/16621517/37558679-db707126-2a17-11e8-89dd-92ba0722e76b.png)

### Steps

1. eg https://utopian.info/moderator/andrejcibik
2. click the repository name

- Browser: Chrome 64
- OS: Windows 10

**Comment by amosbastian** [comment]
https://github.com/amosbastian/utopian/commit/6c2496e6b8019c18be82c467ce709ac817983e4d

Thanks, just fixed it @espoem.
