### ISSUE TITLE
Incorrect review score on a post. 

### ISSUE THREAD

**Issue by HarryHeights** [amosbastian/utopian.rocks#39]
On the website, Utopian contributors can see the review score of their contributions. The review score is based on the review of the moderator using the questionnaire.

However, I noticed a post on the voting queue showing a wrong review score. The post's actual score was 69 when checked on the questionnaire. But on the website(Utopian.rocks) a score of zero is shown, 

I tried to find out if other posts had same issue, but, it would have been too stressful to do. This one was outright obvious.  

I don't think providing my device specifications would matter. 

Here's a video of the error.

https://youtu.be/mt0Gyo08Ewk

**Comment by amosbastian** [comment]
Thanks for reporting this, but it's because someone manually set the score to 0 and not something wrong with utopian.rocks.

**Comment by HarryHeights** [comment]
oh okay
