### ISSUE TITLE
New scores are not reflected on the website. 

### ISSUE THREAD

**Issue by HarryHeights** [amosbastian/utopian.rocks#42]
#### Expected Behaviour

I expected that if a post was re-reviewed and is now having a new score, it would reflect on the website. 

#### Actual Behaviour

After a post is re-reviewed and is having a new score, the new score doesn't reflect on the website. It still maintains the old score. 

#### Test Enviroment

Browser; Brave Browser

#### Screen recording. 

https://youtu.be/MhAz0THAjU4

**Comment by amosbastian** [comment]
Not an issue with Utopian.rocks.

**Comment by HarryHeights** [comment]
Oh okay.
