### ISSUE TITLE
Suggestion For Utopian.rocks  : Add the "Rejected contributions " and "Gives Start for  for Modrater work " features

### ISSUE THREAD

**Issue by nasirshah1813** [amosbastian/utopian.rocks#43]
![Lovepik_com-400553755-simple-pattern-segmentation-line.png](https://ipfs.busy.org/ipfs/QmUSTNbGyLgEyMAWJ73KEyBj1VpC3hVmzF131cqbPhCfeE)
 # Repository
https://github.com/amosbastian/utopian.rocks
![Lovepik_com-400553755-simple-pattern-segmentation-line.png](https://ipfs.busy.org/ipfs/QmUSTNbGyLgEyMAWJ73KEyBj1VpC3hVmzF131cqbPhCfeE)
# Introduction
https://utopian.rocks/   is a Flask application that indicates unreviewed or pending commitments and pending arbitrator remarks. It additionally incorporates a few endpoints to recover commitments, measurements and a week by week layout for one of Utopian's posts.
![Lovepik_com-400553755-simple-pattern-segmentation-line.png](https://ipfs.busy.org/ipfs/QmUSTNbGyLgEyMAWJ73KEyBj1VpC3hVmzF131cqbPhCfeE)
# Components
The components (Features) I want to suggest is:

Rejected contribution
1-Rejected contribution
2- Gives Start for  for Modrater work
![Lovepik_com-400553755-simple-pattern-segmentation-line.png](https://ipfs.busy.org/ipfs/QmUSTNbGyLgEyMAWJ73KEyBj1VpC3hVmzF131cqbPhCfeE)
# Proposal Description
https://utopian.rocks/ is a website that is built on https://utopian.io, a source of money by working on the https://utopian.io Open Source Project  People around this web site check the  work and their work is done by the moderator again and then they are given vote  on the steemit.com  and they earn lots o money  I want some more options to be add to improve this website so that this web site can be made easier.

## (1)  Rejected contributions 
 i want to add the Rejected contributions  button on this sites  The function of this button will be that show all rejected  posts   Any posts that are canceled will appear on all of them here  The advantage of this button is that any new subscribers that are coming, they can better improve their work by looking at canceled posts.

## (2)      Gives Start for  for Modrater work
This button will be very beneficial, in my view and through this button we can also calculate the modular salary  The function of this button should be that any posters will post when their post is canceled or approved, they will give their review to the moderator exactly how the moderator is working. And this will be reviewed only in the form of a star and only a star, which has done a good job, will be given 5 stars and the work that will be done will be 4 stars and so 3 stars and 2 stars I think many people in this button will give their false reviews to the moderator so I want this button to be shown to the manager only and only and the manager should perform their work star by their 
It will be that the manager of the moderator will be honestly honest give the review  and this will be the benefit of the person who is honest person or hard worker person  get more salary on utopian 

## NOTE  We will only keep this option open for the manager, and for this purpose we will make the password above the button through the HTML, which will only pass to the password and only the manager.

![Lovepik_com-400553755-simple-pattern-segmentation-line.png](https://ipfs.busy.org/ipfs/QmUSTNbGyLgEyMAWJ73KEyBj1VpC3hVmzF131cqbPhCfeE)
# Mockups / Examples

original interface of websites 
![1.png](https://ipfs.busy.org/ipfs/QmVAYPdWWu1aX2STXXznikEcbMs32S3hN6EJ9wBmwoZ8Ts)

when we add rejected contribution button we see like this 

![2.png](https://ipfs.busy.org/ipfs/QmPW8tdfGbFoNr2ZtxP6hgKZTbjWq5gkrkRAKghn6X4wKt)

when we open the reject contribution list we see like this all the post 

![3.jpg](https://ipfs.busy.org/ipfs/QmYBg8TmLGC7SsW29HCAf1v4R2ccJPhKHooS8W7jxJTXsJ)

when we add start Gives Start for  for Modrater work " features 
![4.png](https://ipfs.busy.org/ipfs/QmcvRgX4cTpV1ae7PXF9ragcW55qxYX2sUUTWDabbtrAeJ)

when we clikc on the button we show a password box like this 
![6.jpg](https://ipfs.busy.org/ipfs/QmY6GFRhY5ajjuRTqJJ8EaiSDu3BW5pG4aEhopWiBu4rWA)

when  open the option wee see like this 
![5.jpg](https://ipfs.busy.org/ipfs/QmSaLgf5XPey7a2KGW18Aq1zCUawvzLpwLKY7oBGE5ZXtj)
![Lovepik_com-400553755-simple-pattern-segmentation-line.png](https://ipfs.busy.org/ipfs/QmUSTNbGyLgEyMAWJ73KEyBj1VpC3hVmzF131cqbPhCfeE)
# Benefits
## 1 Rejected contributions
New users coming through this option will get many information about working and they will improve their work better When a user sees other user's errors, they will avoid repeating this error

## 2  Gives Start for  for Modrater work

These modular seals can be improved which moderators will be working harder.And the moderators who do not work well will also try to improve their work And the way the moderator works, the salary will continue to increase
![Lovepik_com-400553755-simple-pattern-segmentation-line.png](https://ipfs.busy.org/ipfs/QmUSTNbGyLgEyMAWJ73KEyBj1VpC3hVmzF131cqbPhCfeE)
# GitHub Account
https://github.com/nasirshah1813

**Comment by amosbastian** [comment]
I am not going to implement any of this since I am busy, and Utopian Colony is coming soon, which is a lot more suited to these type of features. Moreover there isn't really much, or any, rejection anymore, so it doesn't make sense to have a "rejected contributions" page.

>The advantage of this button is that any new subscribers that are coming, they can better improve their work by looking at canceled posts.

Either way, it's imo better for them to use good posts as an example of what to do, instead of looking at bad posts as an example of what not to do.

**Comment by nasirshah1813** [comment]
yes sir i know your are busy  on Utopian Colony but according to me you can also add this feature on Utopian Colony if you feel this is useful for user

**Comment by amosbastian** [comment]
I am not working on Utopian Colony, and I am not sure if this is already planned or not. You are better off checking out https://github.com/utopian-io/colony.
