### ISSUE TITLE
Moderating since changes based on tab selection

### ISSUE THREAD

**Issue by tobias-g1** [amosbastian/utopian.rocks#7]
#### Expected

The moderating since date should remain the same regardless of which tab you have selected when viewing a Utopian moderators profile. I should be able to move between moderating to reviews, activity and contributors and it remains the same. It should always reflect the date the moderator completed his first moderation. 

#### Actual

The moderating since date changes to today's date when you switch to activity or contributors. 

#### Steps to reproduce

Simply switch between the different tabs on a moderators profile page and take note of the date shown. The following image should explain more:

The following image shows the moderating since date when reviews is selected:

![image](https://user-images.githubusercontent.com/17148879/39100592-87e3b62a-4683-11e8-8a2d-e8678b274676.png)

The following image show when the contributor's tab is selected:

![image](https://user-images.githubusercontent.com/17148879/39100603-de3fdc10-4683-11e8-81a5-f439ec2ffd79.png)

**Comment by amosbastian** [comment]
Thanks @tobias-g1 I know what's causing it, but I am currently reworking the entire application structure so  it will probably be fixed in a few weeks - I'll leave it as is on the live version for now.
